export const frasesLoading = [
    "Carregando sorrisos...",
    "Respire fundo. Estamos quase lá!",
    "A paciência é uma virtude. Obrigado por esperar!",
    "Carregando doses de felicidade para o seu dia!",
    "Enquanto isso, espalhe gentileza ao seu redor.",
    "Alguém realmente lê isso?",
    "Mostre que você sabe.",
    "F internet",
    "Talvez nos próximos segundos", 
    "Adivinhando o futuro... Quase lá!",
    "Pensando em piadas engraçadas...",
    "Contando até infinito...",
    "Fazendo café virtual... A caminho!", 
    "Inventando desculpas criativas...",
    "Escrevendo o próximo best-seller!!",
    "Criando conspirações sobre gatos!", 
    "Descobrindo o significado da vida... Em análise profunda!", 
    "Fazendo uma pausa criativa.", 
];
