export const frasesSearch = [
    "Acessórios",
    "Eletrônicos",
    "Manutenção",
    "Onix 2018",
    "Ferramentas Automotivas", 
    "Polimento de Faróis",
    "Reparo de Pintura",
    "Martelinho de Ouro",
    "Lavagem a Vapor",
    "Kit de Embreagem",
    "Kit de Correia Dentada",
    "Filtros de Ar Condicionado",
    "Velas de Ignição",
    "Sistema de Arrefecimento",
    "Lubrificantes",
    "Pistões e Anéis",
    "Cabos de Vela",
    "Direção Hidráulica",
    "Jogo de Juntas",
    "Radiadores",
    "Mangueiras e Conexões",
    "Bateria Automotiva",
    "Ignição Eletrônica",
    "Sistema de Freios ABS",
    "Airbags",
    "Cintos de Segurança",
    "Reparo de Transmissão",
    "Correias Automotivas",
    "Bomba de Combustível",
    "Sensores de Oxigênio",
    "Sistema de Escape",
    "Pistões e Bielas",
    "Filtro de Combustível",
    "Embreagem",
    "Bombas de Óleo",
    "Sistema de Direção",
    "Caixa de Câmbio",
    "Jogo de Rolamentos",
    "Reguladores de Pressão",
    "Bicos Injetores",
    "Sistema Elétrico",
    "Alternadores",
    "Motor de Partida",
    "Distribuidores de Ignição",
    "Sistema de Suspensão",
    "Amortecedores",
    "Molas",
    "Barras Estabilizadoras",
    "Buchas",
    "Sistema de Transmissão",
    "Embreagens de Tração",
    "Eixos",
    "Diferenciais",
  ];
  
